### ISSUE TITLE
复现 crashinterceptor 输出的panic 日志堆栈没到logic中 #1204

### ISSUE THREAD

**Issue by LeeDF** [zeromicro/go-zero#1216]
复现https://github.com/zeromicro/go-zero/issues/1204 ， demo地址 https://github.com/LeeDF/zerologs, 日志如下

```
{"@timestamp":"2021-11-09T11:28:34.166+08","level":"error","content":"crashinterceptor.go:42 test goroutine 32 [running]:\nruntime/debug.Stack(0x0, 0xc000112b40, 0xc00060a2a0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.toPanicError(0x1823260, 0x1a469b0, 0xc000270d98, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/crashinterceptor.go:42 +0x26\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryStatInterceptor.func1.1(0x1823260, 0x1a469b0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/statinterceptor.go:22 +0x3e\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.handleCrash(0xc000271860)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/crashinterceptor.go:37 +0x5a\npanic(0x1823260, 0x1a469b0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/tal-tech/go-zero/core/breaker.(*googleBreaker).doReq.func1(0xc0001905d0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/googlebreaker.go:75 +0x85\npanic(0x1823260, 0x1a469b0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1(0x1a67c20, 0xc000042ba0, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001905a0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x3f6\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0x0, 0x100fa18, 0x38, 0x18e92c0)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnarySheddingInterceptor.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001bb040, 0x0, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/sheddinginterceptor.go:43 +0x131\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00019d3d8, 0x16ff61c, 0x0, 0xc014000000000000)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryBreakerInterceptor.func1.1(0xc0001905d0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/breakerinterceptor.go:27 +0x57\ngithub.com/tal-tech/go-zero/core/breaker.(*googleBreaker).doReq(0xc0001905d0, 0xc0001baf00, 0x0, 0xc0001bb000, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/googlebreaker.go:79 +0xd0\ngithub.com/tal-tech/go-zero/core/breaker.loggedThrottle.doReq(0x198038b, 0x1f, 0x1a5df20, 0xc0001905d0, 0xc00060a230, 0xc0001baf00, 0x0, 0x19a5d30, 0x310000c0001905d0, 0xc00060a230)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/breaker.go:172 +0xa7\ngithub.com/tal-tech/go-zero/core/breaker.(*circuitBreaker).DoWithAcceptable(0xc00007c0a0, 0xc0001baf00, 0x19a5d30, 0x1a6b358, 0xc0001905b8)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/breaker.go:122 +0x51\ngithub.com/tal-tech/go-zero/core/breaker.DoWithAcceptable.func1(0x1a6b358, 0xc00007c0a0, 0x1a6b358, 0xc00007c0a0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/breakers.go:20 +0x43\ngithub.com/tal-tech/go-zero/core/breaker.do(0x198038b, 0x1f, 0xc00019d5f8, 0x100fa18, 0x38)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/breakers.go:67 +0x52\ngithub.com/tal-tech/go-zero/core/breaker.DoWithAcceptable(0x198038b, 0x1f, 0xc0001baf00, 0x19a5d30, 0xc0001baec0, 0xc00019d668)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/core/breaker/breakers.go:19 +0x70\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryBreakerInterceptor.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001baec0, 0xc0001baec0, 0xc0001bae80, 0x40, 0x38)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/breakerinterceptor.go:25 +0xfe\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc000100900, 0x0, 0xc00019d758, 0x100fa18)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryPrometheusInterceptor.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001bae80, 0xc0001bae80, 0xc05a989889d424d0, 0x47f12c94c, 0x1f6db20)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/prometheusinterceptor.go:41 +0x325\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0x38, 0x38, 0x216da68, 0x40)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryStatInterceptor.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001bae40, 0x0, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/statinterceptor.go:34 +0x17a\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0x100fa18, 0x38, 0x18e92c0, 0x18ed201)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryCrashInterceptor.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001bae00, 0x0, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/crashinterceptor.go:31 +0xb7\ngoogle.golang.org/grpc.getChainUnaryHandler.func1(0x1a67c58, 0xc000112780, 0x18fade0, 0xc0001125a0, 0xc000114060, 0x10, 0x198038b, 0x1f)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1133 +0xe7\ngithub.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTracingInterceptor.func1(0x1a67c58, 0xc000112570, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001badc0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.10/zrpc/internal/serverinterceptors/tracinginterceptor.go:27 +0x225\ngoogle.golang.org/grpc.chainUnaryServerInterceptors.func1(0x1a67c58, 0xc000112570, 0x18fade0, 0xc0001125a0, 0xc00007c080, 0xc0001905a0, 0xc00011bba0, 0x1106f66, 0x18ed260, 0xc000112570)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119 +0xd0\ngithub.com/LeeDF/zerologs/rpc/helloService/helloService._HelloService_Ping_Handler(0x184b000, 0xc00013e040, 0x1a67c58, 0xc000112570, 0xc000042a80, 0xc00013c880, 0x1a67c58, 0xc000112570, 0xc000114198, 0x5)\n\t/Users/ldf/code/github.com/zerologs/rpc/helloService/helloService/helloService.pb.go:189 +0x150\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc00016e1c0, 0x1a6f4d8, 0xc000472180, 0xc0002bc240, 0xc000392900, 0x1f53830, 0x0, 0x0, 0x0)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b\ngoogle.golang.org/grpc.(*Server).handleStream(0xc00016e1c0, 0x1a6f4d8, 0xc000472180, 0xc0002bc240, 0x0)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000434060, 0xc00016e1c0, 0x1a6f4d8, 0xc000472180, 0xc0002bc240)\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940 +0xab\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/Users/ldf/code/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd\n"}
```

**Comment by kevwan** [comment]
The issue was fixed already, use go-zero v1.2.2, you'll get the following log

```
crashinterceptor.go:40 test

goroutine 74 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()
	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46
panic({0x2166480, 0x25e0630})
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
github.com/LeeDF/zerologs/rpc/helloService/internal/logic.(*PingLogic).Ping(...)
	/Users/kevin/temp/issue/zerologs/rpc/helloService/internal/logic/pinglogic.go:28
github.com/LeeDF/zerologs/rpc/helloService/internal/server.(*HelloServiceServer).Ping(0xc000141310, {0x261c920, 0xc00031c4e0}, 0x0)
	/Users/kevin/temp/issue/zerologs/rpc/helloService/internal/server/helloserviceserver.go:26 +0x71
github.com/LeeDF/zerologs/rpc/helloService/helloService._HelloService_Ping_Handler.func1({0x261c920, 0xc00031c4e0}, {0x22fa1c0, 0xc0003d6cf0})
	/Users/kevin/temp/issue/zerologs/rpc/helloService/helloService/helloService.pb.go:187 +0x78
github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()
	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f
created by github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1
	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x251
```

**Comment by LeeDF** [comment]
> The issue was fixed already, use go-zero v1.2.2, you'll get the following log
> 
> ```
> crashinterceptor.go:40 test
> 
> goroutine 74 [running]:
> runtime/debug.Stack()
> 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/debug/stack.go:24 +0x65
> github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()
> 	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46
> panic({0x2166480, 0x25e0630})
> 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
> github.com/LeeDF/zerologs/rpc/helloService/internal/logic.(*PingLogic).Ping(...)
> 	/Users/kevin/temp/issue/zerologs/rpc/helloService/internal/logic/pinglogic.go:28
> github.com/LeeDF/zerologs/rpc/helloService/internal/server.(*HelloServiceServer).Ping(0xc000141310, {0x261c920, 0xc00031c4e0}, 0x0)
> 	/Users/kevin/temp/issue/zerologs/rpc/helloService/internal/server/helloserviceserver.go:26 +0x71
> github.com/LeeDF/zerologs/rpc/helloService/helloService._HelloService_Ping_Handler.func1({0x261c920, 0xc00031c4e0}, {0x22fa1c0, 0xc0003d6cf0})
> 	/Users/kevin/temp/issue/zerologs/rpc/helloService/helloService/helloService.pb.go:187 +0x78
> github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()
> 	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f
> created by github.com/tal-tech/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1
> 	/Users/kevin/Develop/go/pkg/mod/github.com/tal-tech/go-zero@v1.2.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x251
> ```

Which commit was fixed and I want to know why？

**Comment by kevwan** [comment]
I guess the call depth was passed incorrectly.  Lots of commits happened already.

**Comment by LeeDF** [comment]
> I guess the call depth was passed incorrectly. Lots of commits happened already.

ok
