### ISSUE TITLE
Throw out of memory when installing goctl

### ISSUE THREAD

**Issue by Jungle-Leung** [zeromicro/go-zero#1762]
Dockerfile：
```
FROM golang:1.16.0-alpine3.13

#ENV ALPINE_VERSION v3.13
ENV GO111MODULE on
ENV GOPROXY https://goproxy.cn/,direct
ENV GOMODCACHE $GOPATH/pkg/mod

# 安装goctl
RUN go install github.com/zeromicro/go-zero/tools/goctl@latest; \
    \
    # 安装protoc & protoc-gen-go
    goctl env check -i -f; \
    \
    # 设置protoc权限
    chmod -R 775 /go/bin

WORKDIR /var/www/greet

CMD /bin/sh
```

docker build：
```
docker build --no-cache -t goz ./
```

result：
```
root@VM-12-17-ubuntu:/var/www/go-zero# docker build --no-cache -t goz ./
Sending build context to Docker daemon  1.902MB
Step 1/7 : FROM golang:1.16.0-alpine3.13
 ---> 696265badec1
Step 2/7 : ENV GO111MODULE on
 ---> Running in a531b586496b
Removing intermediate container a531b586496b
 ---> 7fee0d3fdcbe
Step 3/7 : ENV GOPROXY https://goproxy.cn/,direct
 ---> Running in f722345e09de
Removing intermediate container f722345e09de
 ---> 89f4bb018381
Step 4/7 : ENV GOMODCACHE $GOPATH/pkg/mod
 ---> Running in f69c2b5301b0
Removing intermediate container f69c2b5301b0
 ---> f6a542d51e60
Step 5/7 : RUN go install github.com/zeromicro/go-zero/tools/goctl@latest;         goctl env check -i -f;         chmod -R 775 /go/bin
 ---> Running in d4f2fddee577
go: downloading github.com/zeromicro/go-zero v1.3.2
go: downloading github.com/zeromicro/go-zero/tools/goctl v1.3.4
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/urfave/cli v1.22.5
go: downloading go.opentelemetry.io/otel v1.3.0
go: downloading go.opentelemetry.io/otel/trace v1.3.0
go: downloading github.com/iancoleman/strcase v0.2.0
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading go.uber.org/automaxprocs v1.4.0
go: downloading github.com/fatih/structtag v1.2.0
go: downloading github.com/zeromicro/antlr v0.0.1
go: downloading github.com/lib/pq v1.10.4
go: downloading github.com/emicklei/proto v1.9.1
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/zeromicro/ddl-parser v1.0.3
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210521184019-c5ad59b459ec
# github.com/zeromicro/ddl-parser/gen
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xcac67f, 0x16)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc054000000, 0x4000000, 0x11e7b90)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x11c8bc0, 0x400000, 0x7fffffffffff, 0x1c0)
	/usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x11c8bc0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x11c8bc0, 0x1, 0x440c00, 0x7f770f723f50)
	/usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x46d334)
	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc02dd26f78 sp=0xc02dd26f70 pc=0x46d460
runtime.(*mheap).alloc(0x11c8bc0, 0x1, 0x43010c, 0x11d9798)
	/usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc02dd26fc8 sp=0xc02dd26f78 pc=0x4279a5
runtime.(*mcentral).grow(0x11d96f8, 0x0)
	/usr/local/go/src/runtime/mcentral.go:232 +0x79 fp=0xc02dd27010 sp=0xc02dd26fc8 pc=0x418a59
runtime.(*mcentral).cacheSpan(0x11d96f8, 0x7f770f724170)
	/usr/local/go/src/runtime/mcentral.go:158 +0x2ff fp=0xc02dd27068 sp=0xc02dd27010 pc=0x41883f
runtime.(*mcache).refill(0x7f773afb65b8, 0xc)
	/usr/local/go/src/runtime/mcache.go:162 +0xaa fp=0xc02dd270b0 sp=0xc02dd27068 pc=0x417d4a
runtime.(*mcache).nextFree(0x7f773afb65b8, 0xc, 0x8, 0x0, 0x7f770f723f50)
	/usr/local/go/src/runtime/malloc.go:882 +0x8d fp=0xc02dd270e8 sp=0xc02dd270b0 pc=0x40d38d
runtime.mallocgc(0x40, 0xc715c0, 0x1, 0x8)
	/usr/local/go/src/runtime/malloc.go:1069 +0x850 fp=0xc02dd27170 sp=0xc02dd270e8 pc=0x40dd90
runtime.newobject(0xc715c0, 0x20)
	/usr/local/go/src/runtime/malloc.go:1177 +0x38 fp=0xc02dd271a0 sp=0xc02dd27170 pc=0x40dff8
cmd/compile/internal/types.NewField(...)
	/usr/local/go/src/cmd/compile/internal/types/type.go:587
cmd/compile/internal/gc.structfield(0xc053ffb980, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:546 +0x65 fp=0xc02dd27200 sp=0xc02dd271a0 pc=0xa5e685
cmd/compile/internal/gc.tofunargs(0xc04bb741d0, 0x1, 0x1, 0xc02dd27202, 0xc053ffe000)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:629 +0xc5 fp=0xc02dd27258 sp=0xc02dd27200 pc=0xa5ee45
cmd/compile/internal/gc.functype(0x0, 0xc04bb741d0, 0x1, 0x1, 0xc04bb741d8, 0x1, 0x1, 0x40)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:729 +0x12b fp=0xc02dd27338 sp=0xc02dd27258 pc=0xa5f7cb
cmd/compile/internal/gc.methodfunc(0xc009cb29c0, 0xc00a969860, 0xc01684ea20)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:372 +0x43f fp=0xc02dd27410 sp=0xc02dd27338 pc=0xaf055f
cmd/compile/internal/gc.methods(0xc00a969860, 0xc03062ee00, 0x13, 0x20)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:430 +0x23f fp=0xc02dd27510 sp=0xc02dd27410 pc=0xaf0bbf
cmd/compile/internal/gc.genfun(0xc00a969860, 0xc009ca0480, 0x44eb4cf5, 0x4, 0x14)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1463 +0xab fp=0xc02dd275c8 sp=0xc02dd27510 pc=0xaf7a2b
cmd/compile/internal/gc.dumptabs()
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1574 +0x225 fp=0xc02dd276d0 sp=0xc02dd275c8 pc=0xaf8545
cmd/compile/internal/gc.dumpdata()
	/usr/local/go/src/cmd/compile/internal/gc/obj.go:125 +0x8f fp=0xc02dd27760 sp=0xc02dd276d0 pc=0xac842f
cmd/compile/internal/gc.Main(0xcc7d20)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:803 +0x382b fp=0xc02dd27f10 sp=0xc02dd27760 pc=0xaabeeb
main.main()
	/usr/local/go/src/cmd/compile/main.go:52 +0xb1 fp=0xc02dd27f88 sp=0xc02dd27f10 pc=0xbf90d1
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc02dd27fe0 sp=0xc02dd27f88 pc=0x439d76
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc02dd27fe8 sp=0xc02dd27fe0 pc=0x46f161
/bin/sh: goctl: not found
Removing intermediate container d4f2fddee577
 ---> 7fe38e1ec7a6
Step 6/7 : WORKDIR /var/www/greet
 ---> Running in 9a532f8727ee
Removing intermediate container 9a532f8727ee
 ---> d74682f908d8
Step 7/7 : CMD /bin/sh
 ---> Running in 7a3f8d7d969f
Removing intermediate container 7a3f8d7d969f
 ---> 5984cdbf2ede
Successfully built 5984cdbf2ede
```

**Comment by Jungle-Leung** [comment]
My machine configuration：
CPU：2 core 
MEMORY：2048MB

**Comment by kevwan** [comment]
4G at least.

**Comment by Jungle-Leung** [comment]
> 4G at least.
