### ISSUE TITLE
引入第三方 proto 报错

### ISSUE THREAD

**Issue by Ccheers** [zeromicro/go-zero#3056]
**Describe the bug**

goctl rpc protoc pb/auth_rpc.proto --go-grpc_out=paths=source_relative:. --go_out=paths=source_relative:. --zrpc_out=. -I .
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x15ed67e]

goroutine 1 [running]:
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.findPbFile.func1({0x1b0c610, 0x1}, {0x0?, 0x0?}, {0xc00010eb40?, 0x0?})
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/genpb.go:69 +0x3e
io/fs.WalkDir({0x1b14b60, 0xc00010eb40}, {0x1b0c610, 0x1}, 0xc0005bf870)
E:/go/src/io/fs/walk.go:120 +0x6a
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.findPbFile({0xc000050d80, 0x59}, 0x0)
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/genpb.go:68 +0xa5
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.(*Generator).setPbDir(0xc00005aa80?, {0x1b39498, 0xc000397980}, 0xc000122d80)
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/genpb.go:34 +0x45
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.(*Generator).genPbDirect(0xc000397680, {0x1b39498, 0xc000397980}, 0xc000122d80)
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/genpb.go:30 +0x108
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.(*Generator).GenPb(...)
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/genpb.go:16
github.com/zeromicro/go-zero/tools/goctl/rpc/generator.(*Generator).Generate(0xc000397680, 0xc000122d80)
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/generator/gen.go:73 +0x234
github.com/zeromicro/go-zero/tools/goctl/rpc/cli.ZRPC(0x2ad01c0?, {0xc0004f6ae0?, 0x1, 0x6?})
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/rpc/cli/zrpc.go:106 +0x55a
github.com/spf13/cobra.(*Command).execute(0x2ad01c0, {0xc0004f6a80, 0x6, 0x6})
go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x2accb20)
go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/zeromicro/go-zero/tools/goctl/cmd.Execute()
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/cmd/root.go:51 +0x6a
main.main()
go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.5.0/goctl.go:12 +0x4d

`auth.proto`
```protobuffer
syntax = "proto3";

option go_package = /app/auth/cmd/rpc/pb";

package auth;
import "third_part/test.proto";
```

`test.proto`
```protobuffer
syntax = "proto3";

package authtest;
option go_package = "app/auth/cmd/rpc/third_part;third_part";

message Test1 {
  uint32 id = 1;
}
```

**Comment by anqiansong** [comment]
```
goctl rpc protoc pb/auth_rpc.proto --go-grpc_out=paths=source_relative:. --go_out=paths=source_relative:. --zrpc_out=. -I .
```
Why are you execute in your command is` auth_rpc.proto`, and the actual file is` auth_proto`?. In addition, the service in your proto file is not declared. If you modify the file name, you can replace the command with the following：
```
 goctl rpc protoc pb/auth_rpc.proto --go-grpc_opt=paths=source_relative --go-grpc_out . --go_opt=paths=source_relative --go_out . -I pb --zrpc_out .
```
