### ISSUE TITLE
After api is declared as an array structure, it cannot be generated through goctl swagger

### ISSUE THREAD

**Issue by aarchies** [zeromicro/go-zero#3758]
我定义了一个api文件，并依此成功生成api相关代码
如下
 
![微信截图_20231205161128](https://github.com/zeromicro/go-zero/assets/143398903/8cebd306-90af-4f40-9b77-0c11359e1bd9)
![微信截图_20231205161138](https://github.com/zeromicro/go-zero/assets/143398903/c18dc32a-454d-41c1-8cc3-a3cd4a7af84c)

但是在通过官方 goctl api plugin -plugin goctl-swagger="swagger进行swagger文档生成时，发生报错，
如下：
Error: panic: error: line 52:8 field Nodes has no tag

个人测试，进行匿名声明或注释该数组结构体后可以成功生成，在官方文档没有找到相关可声明数组文档描述

**Comment by aarchies** [comment]
Error: panic: error: line 52:8 field Nodes has no tag

goroutine 1 [running]:
github.com/zeromicro/go-zero/tools/goctl/api/parser.parser.fieldToMember({0xc000112bd0?, 0xc0001160f0?}, 0xc0005b4a20)
        C:/Users/user/go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.3.2/api/parser/parser.go:162 +0x33c
github.com/zeromicro/go-zero/tools/goctl/api/parser.parser.fillTypes({0xc000112bd0?, 0xc0001160f0?})
        C:/Users/user/go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.3.2/api/parser/parser.go:104 +0x8e5
github.com/zeromicro/go-zero/tools/goctl/api/parser.parser.convert2Spec({0xc000112bd0?, 0xc0001160f0?})
        C:/Users/user/go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.3.2/api/parser/parser.go:58 +0x54
github.com/zeromicro/go-zero/tools/goctl/api/parser.Parse({0xc0000ce1e0, 0x4e})
        C:/Users/user/go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.3.2/api/parser/parser.go:28 +0xaf
github.com/zeromicro/go-zero/tools/goctl/plugin.NewPlugin()
        C:/Users/user/go/pkg/mod/github.com/zeromicro/go-zero/tools/goctl@v1.3.2/plugin/plugin.go:181 +0x119
github.com/zeromicro/goctl-swagger/action.Generator(0xc00014e180?)
        C:/Users/user/go/pkg/mod/github.com/zeromicro/goctl-swagger@v0.1.0/action/action.go:16 +0x37
github.com/urfave/cli/v2.(*Command).Run(0xff4300, 0xc00009ee80)
        C:/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x583
github.com/urfave/cli/v2.(*App).RunContext(0xc000084d00, {0xc9e9e8?, 0x1051440}, {0xc0000c0000, 0x6, 0x8})
        C:/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xaa5
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        C:/Users/user/go/pkg/mod/github.com/zeromicro/goctl-swagger@v0.1.0/main.go:42 +0x153

**Comment by aarchies** [comment]
已解决

**Comment by kesonan** [comment]
Thanks for feedback again.
