### ISSUE TITLE
Improve gateway availability, the gateway fails to start if a configured service is not started

### ISSUE THREAD

**Issue by eyjian** [zeromicro/go-zero#3891]
Currently, a certain service is not started, which will cause the gateway to fail to start. The gateway and the service are strongly coupled.

For gateways, this is a serious problem.

If a service is not started, it should not affect the gateway. Maybe the service is not a core service yet.

Example: the gateway failed to start because service "mooonlogin.rpc" did not start.

```
# ./mooon_gateway 
{"@timestamp":"2024-02-05T13:40:49.721+08:00","caller":"mooon-gateway/main.go:24","content":"LoginPrefix: /v1","level":"info"}
{"@timestamp":"2024-02-05T13:40:49.721+08:00","caller":"mooon-gateway/main.go:25","content":"AuthPrefix: /v2","level":"info"}
2024-02-05T13:40:49.721+08:00    info   Starting mooon_gateway at localhost:6688 ...    caller=mooon-gateway/main.go:36
2024-02-05T13:40:49.727+08:00    error  bad resolver state      caller=internal/discovbuilder.go:34
2024/02/05 13:40:52 rpc dial: etcd://127.0.0.1:2379/mooonlogin.rpc, error: context deadline exceeded, make sure rpc service "mooonlogin.rpc" is already started

goroutine 11 [running]:
runtime/debug.Stack()
        /usr/local/go-1.21.5/src/runtime/debug/stack.go:24 +0x5e
github.com/zeromicro/go-zero/core/logx.Must({0x2099360?, 0xc000127080?})
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/logx/logs.go:225 +0x4b
github.com/zeromicro/go-zero/zrpc.MustNewClient({{{0xc00068f7b0, 0x1, 0x1}, {0xc00013da30, 0xe}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/zrpc/client.go:45 +0x65
github.com/zeromicro/go-zero/gateway.(*Server).build.func2({{0xc0004cd6e0, 0x24}, {{{0xc00068f7b0, 0x1, 0x1}, {0xc00013da30, 0xe}, 0x0, {0x0, 0x0}, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/gateway/server.go:72 +0xa5
github.com/zeromicro/go-zero/core/mr.mapReduceWithPanicChan[...].func5({_, _})
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:198 +0x59
github.com/zeromicro/go-zero/core/mr.executeMappers[...].func2()
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:327 +0x15e
created by github.com/zeromicro/go-zero/core/mr.executeMappers[...] in goroutine 82
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:317 +0x1b7
2024-02-05T13:40:52.722+08:00    fatal  rpc dial: etcd://127.0.0.1:2379/mooonlogin.rpc, error: context deadline exceeded, make sure rpc service "mooonlogin.rpc" is already started

goroutine 11 [running]:
runtime/debug.Stack()
        /usr/local/go-1.21.5/src/runtime/debug/stack.go:24 +0x5e
github.com/zeromicro/go-zero/core/logx.Must({0x2099360?, 0xc000127080?})
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/logx/logs.go:225 +0x4b
github.com/zeromicro/go-zero/zrpc.MustNewClient({{{0xc00068f7b0, 0x1, 0x1}, {0xc00013da30, 0xe}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/zrpc/client.go:45 +0x65
github.com/zeromicro/go-zero/gateway.(*Server).build.func2({{0xc0004cd6e0, 0x24}, {{{0xc00068f7b0, 0x1, 0x1}, {0xc00013da30, 0xe}, 0x0, {0x0, 0x0}, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/gateway/server.go:72 +0xa5
github.com/zeromicro/go-zero/core/mr.mapReduceWithPanicChan[...].func5({_, _})
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:198 +0x59
github.com/zeromicro/go-zero/core/mr.executeMappers[...].func2()
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:327 +0x15e
created by github.com/zeromicro/go-zero/core/mr.executeMappers[...] in goroutine 82
        /root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/mr/mapreduce.go:317 +0x1b7
```

**Comment by kevwan** [comment]
If not check at the start, when to check the routes? For some scenarios, we load the routes from the server directly, how to know the server is started?

We can have more discussion on this. If any better solution, we'll change the implementation. Thanks!

**Comment by eyjian** [comment]
A health check mechanism is needed here. Simply retry regularly. In short, the gateway cannot be started just because a service is not started. In fact, what happens after startup does not affect the gateway, and the behavior here is inconsistent. If there is no gateway, it will not be able to get up because the proxy service is not up. This is just a service that is unavailable. The implementation here at least allows the user to decide whether to apply "MUST" semantics, and the current implementation has no choice.

**Comment by eyjian** [comment]
Of course, error logs are necessary. Although errors will not cause the gateway to fail to start, they must be discovered by operation and maintenance. Monitoring and alarm capabilities also need to be provided here. However, this is not for the startup of the gateway, but for the needs of service availability management.

**Comment by eyjian** [comment]
Because one service is unavailable, all services are unavailable. Obviously no company can accept this. The gateway must be decoupled from the service, but the gateway must be able to eliminate faulty services and detect service recovery, and it needs to have reasonable detection mechanism.
