### ISSUE TITLE
Goland IDE plug-in bug?

### ISSUE THREAD

**Issue by pashifika** [zeromicro/go-zero#4403]
**Describe the bug**

Goland Version: 2024.2.3
Goctl plug-in Version: 1.1.9

**To Reproduce**
Steps to reproduce the behavior, if applicable:

The new UI is enable.

2. The error is

   ```
   com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cn.xiaoheiban.action.ApiNewAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cn.xiaoheiban.go-zero]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: mac os 15.0
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by kesonan** [comment]
This will not affect the use of the plug-in. The knowledge reminder is that the internal components are out of date. Many plug-ins have this problem.
